name: processing
channels:
  - conda-forge
  - defaults
dependencies:
  - jupyterlab
  - matplotlib
  - numpy=1.21.2
  - pandas=1.3.4
  - pip=22.0.4
  - python=3.7
  - seaborn=0.11.2
  - pip:
    - tweepy==4.1.0
    - wget==3.2

